# Generated by Django 3.1.6 on 2021-03-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='content_objects',
            new_name='content_object',
        ),
    ]
