# Generated by Django 3.1.6 on 2021-03-26 05:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('blog', '0008_blogpageindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageIndexPage',
            new_name='BlogTagIndexPage',
        ),
    ]
